<%@page import="java.util.HashMap"%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<c:set var="filterMap" value="<%= new HashMap<String, String>() %>" />
${filterMap.put("편의점", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_convenient_store_dark_secondary_normal_25px.png")}
${filterMap.put("욕실용품", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_bath_supplies_dark_secondary_normal_25px.png")}
${filterMap.put("주차장", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_parking_dark_secondary_normal_25px.png")}
${filterMap.put("냉장고", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_refrigerator_dark_secondary_normal_25px.png")}
${filterMap.put("미니바", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_mini_bar_dark_secondary_normal_25px.png")}
${filterMap.put("객실샤워실", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_shower_dark_secondary_normal_25px.png")}
${filterMap.put("욕조", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_bath_tub_dark_secondary_normal_25px.png")}
${filterMap.put("캠프파이어", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_campfire_dark_secondary_normal_25px.png")}
${filterMap.put("수영장", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_pool_dark_secondary_normal_25px.png")}
${filterMap.put("전기사용가능", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_electricity_dark_secondary_normal_25px.png")}
${filterMap.put("드라이기", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_hair_dryer_dark_secondary_normal_25px.png")}
${filterMap.put("세면도구", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_toiletries_dark_secondary_normal_25px.png")}
${filterMap.put("픽업가능", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_pick_up_dark_secondary_normal_25px.png")}
${filterMap.put("반려견동반", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_pet_friendly_dark_secondary_normal_25px.png")}
${filterMap.put("전기밥솥", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_electric_cooker_dark_secondary_normal_25px.png")}
${filterMap.put("사이트주차", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_parking_in_site_dark_secondary_normal_25px.png")}
${filterMap.put("건조기", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_dryer_dark_secondary_normal_25px.png")}
${filterMap.put("공용화장실", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_lavatory_dark_secondary_normal_25px.png")}
${filterMap.put("매점", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_snack_bar_dark_secondary_normal_25px.png")}
${filterMap.put("공용샤워실", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_shared_shower_dark_secondary_normal_25px.png")}
${filterMap.put("무료주차", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_free_parking_dark_secondary_normal_25px.png")}
${filterMap.put("인터넷", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_internet_dark_secondary_normal_25px.png")}
${filterMap.put("객실스파", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_spa_dark_secondary_normal_25px.png")}
${filterMap.put("BBQ", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_bbq_dark_secondary_normal_25px.png")}
${filterMap.put("와이파이", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_wifi_dark_secondary_normal_25px.png")}
${filterMap.put("객실내흡연", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_smoking_friednly_dark_secondary_normal_25px.png")}
${filterMap.put("세탁기", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_laundry_dark_secondary_normal_25px.png")}
${filterMap.put("객실내취사", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_indoor_cooking_friendly_dark_secondary_normal_25px.png")}
${filterMap.put("물놀이시설", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_paddling_pool_dark_secondary_normal_25px.png")}
${filterMap.put("에어컨", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_air_conditioner_dark_secondary_normal_25px.png")}
${filterMap.put("카페", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_cafe_dark_secondary_normal_25px.png")}
${filterMap.put("금연", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_smoke_free_dark_secondary_normal_25px.png")}
${filterMap.put("개수대", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_outdoor_sink_dark_secondary_normal_25px.png")}
${filterMap.put("카드결제", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_credit_card_dark_secondary_normal_25px.png")}
${filterMap.put("TV", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_tv_dark_secondary_normal_25px.png")}
${filterMap.put("욕실용품", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_bath_supplies_dark_secondary_normal_25px.png")}
${filterMap.put("라운지", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_lounge_dark_secondary_normal_25px.png")}
${filterMap.put("장비대여", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_rental_service_dark_secondary_normal_25px.png")}
${filterMap.put("전자레인지", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_microwave_dark_secondary_normal_25px.png")}
${filterMap.put("조식포함", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_breakfast_dark_secondary_normal_25px.png")}
${filterMap.put("취사가능", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_cooking_friendly_dark_secondary_normal_25px.png")}
${filterMap.put("탈수기", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_spin_dryer_dark_secondary_normal_25px.png")}
${filterMap.put("노래방", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_karaoke_dark_secondary_normal_25px.png")}
${filterMap.put("주방/식당", "//image.goodchoice.kr/images/web_v3/theme/ic_facility_kitchen_dark_secondary_normal_25px.png")}